In [3]:
import numpy as np
mat1=np.empty((3,3))
mat2=np.empty((3,3))

print("Enter the elements of first matrix: ")

for i in range(0,3):
    for j in range(0,3):
        mat1[i][j]=int(input(f"Enter element {i},{j} of matrix 1: "))
        mat2[i][j]=int(input(f"Enter element {i},{j} of matrix 2: "))

print(f"Matrix1 \n {mat1}")
print(f"Matrix2 \n {mat2}")

Enter the elements of first matrix: 
Matrix1 
 [[3. 3. 2.]
 [4. 2. 6.]
 [6. 4. 3.]]
Matrix2 
 [[5. 5. 8.]
 [7. 6. 3.]
 [3. 7. 7.]]


Transpose

In [4]:

transpose=np.transpose(mat1)
print(f"Transpose is : \n {transpose}")

Transpose is : 
 [[3. 4. 6.]
 [3. 2. 4.]
 [2. 6. 3.]]


Dot Product

In [11]:
print("direct multilplication")
print(mat1*mat2) #direct multilplication
print("Matrix Multiplication: ")
print(np.dot(mat1,mat2))

direct multilplication
[[15. 15. 16.]
 [28. 12. 18.]
 [18. 28. 21.]]
Matrix Multiplication: 
[[42. 47. 47.]
 [52. 74. 80.]
 [67. 75. 81.]]


Trace

In [9]:
print(mat2)
print(f"diagonal sum: {np.trace(mat2)}") 

[[5. 5. 8.]
 [7. 6. 3.]
 [3. 7. 7.]]
diagonal sum: 18.0


DETERMINENT

In [12]:
print(mat1)
print(f"The Determinent is {np.linalg.det(mat1)}")

[[3. 3. 2.]
 [4. 2. 6.]
 [6. 4. 3.]]
The Determinent is 25.99999999999999


INVERSE,RANK,EIGEN VALUES AND VECTORS

In [17]:
print(mat1)
print(f"Inverse: \n {np.linalg.inv(mat1)}") 
print(f"Rank: \n {np.linalg.matrix_rank(mat1)}") 
print(f"Eigen values: \n {np.linalg.eig(mat1).eigenvalues}") 
print(f"\nEigen vectors: \n {np.linalg.eig(mat1).eigenvectors}")  

[[3. 3. 2.]
 [4. 2. 6.]
 [6. 4. 3.]]
Inverse: 
 [[-0.69230769 -0.03846154  0.53846154]
 [ 0.92307692 -0.11538462 -0.38461538]
 [ 0.15384615  0.23076923 -0.23076923]]
Rank: 
 3
Eigen values: 
 [10.73950796+0.j        -1.36975398+0.7380661j -1.36975398-0.7380661j]

Eigen vectors: 
 [[ 0.41474214+0.j         -0.46549102-0.17990077j -0.46549102+0.17990077j]
 [ 0.63635749+0.j          0.82387441+0.j          0.82387441-0.j        ]
 [ 0.6504138 +0.j         -0.15238166+0.22127947j -0.15238166-0.22127947j]]
