In [2]:
import numpy as np
from numpy import random

PROGRAM 1

In [3]:
f=np.array((-40,30,32,23))

# for num in f:
#     c.append((num-32)*(5/9))
c=(f-32)*(5/9)
print(c)

[-40.          -1.11111111   0.          -5.        ]


PROGRAM 2

In [11]:
arr = random.randint(100,size=(1000))
var = np.var(arr)
mean= np.mean(arr)
std= np.std(arr)
print(f"Mean is {mean}\nVarience is {var}\nSd is {std}")

Mean is 49.207
Varience is 806.9961509999999
Sd is 28.407677676994293


PROGRAM 3

In [16]:
angles=random.randint(360,size=(10))

radians=np.radians(angles)
print(angles)
print(radians)

[ 67   8 340  44 266 177 190 294 240  65]
[1.1693706  0.13962634 5.93411946 0.76794487 4.64257581 3.08923278
 3.31612558 5.131268   4.1887902  1.13446401]


PROGRAM 4

In [22]:
arr=random.randint(20,size=(10))
difference=np.diff(arr)
print(arr)
print(difference)

[10 16  8 10  3 11  5  8 11 18]
[ 6 -8  2 -7  8 -6  3  3  7]


PROGRAM 5

In [32]:
arr=np.array([1+2j,3-1j,1-5j,30-2j,12-7j])
sorted=np.sort_complex(arr)
print(sorted)

[ 1.-5.j  1.+2.j  3.-1.j 12.-7.j 30.-2.j]


PROGRAM 6

In [54]:
arr=random.randint(0,20,size=(10))
print(arr)
print([x for x in arr if x>4])

[ 3 18  5  0 11 17  0  1  0 14]
[18, 5, 11, 17, 14]


PROGRAM 7

In [6]:
arr=random.randint(0,20,size=(10))
print(arr)
k=int(input("Enter the number to search: "))
found=0
for i in range(0,10):
    if arr[i]==k:
        print(f"found at {i}")
        found=1
if(found==0):
   print("Not Found")

[15 10  1 14  0 13 15 17 11  8]
Not Found


PROGRAM 8

In [9]:
arr=np.array([2,3,6,1,6,9])
np.savetxt("nums.txt",arr)
loaded=np.loadtxt("nums.txt")
print(f"The loaded text is {loaded}")


The loaded text is [2. 3. 6. 1. 6. 9.]


PROGRAM 9

In [10]:
evenarr=np.arange(30,61,2)
print(evenarr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


PROGRAM 10

In [17]:
arr=random.randint(1,8,size=(3,3))
print(arr)
allsum=np.sum(arr)
colsum=np.sum(arr,axis=0)
rowsum=np.sum(arr,axis=1)
print(f"All sum: {allsum}")
print(f"Col sum: {colsum}")
print(f"Row sum: {rowsum}")

[[7 3 5]
 [4 6 3]
 [5 1 3]]
All sum: 37
Col sum: [16 10 11]
Row sum: [15 13  9]
