In [12]:
import numpy as np
arr=np.arange(2,8)
print(arr)
print(arr[1:5])
print(arr[:5])
print(arr[3:])
print(arr[-4:-1])
print(arr[-1:-4:-1])

[2 3 4 5 6 7]
[3 4 5 6]
[2 3 4 5 6]
[5 6 7]
[4 5 6]
[7 6 5]


In [ ]:
arr1=np.arange(2,10)
arr2=arr1
arr2[2]=10
print(arr1)
print(arr2)


[ 2  3 10  5  6  7  8  9]
[ 2  3 10  5  6  7  8  9]


In [15]:
arr1=np.arange(2,10)
arr2=np.copy(arr1)
arr2[2]=10
print(arr1)
print(arr2)


[2 3 4 5 6 7 8 9]
[ 2  3 10  5  6  7  8  9]


In [19]:
a=np.arange(1,10)
b=np.arange(11,20)
print(a,b)
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [ ]:
mat1=np.array(([1,2,3],[4,5,6]))
mat2=np.array(([11,22],[44,55]))
print(mat1)
print(mat2)
# mat3=np.concatenate((mat1,mat2)) without axis leads to error
mat3=np.concatenate((mat1,mat2),axis=1)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[11 22]
 [44 55]]
[[ 1  2  3 11 22]
 [ 4  5  6 44 55]]


In [29]:
mat1=np.array(([1,2],[4,5]))
mat2=np.array(([11,22],[44,55]))

mat3=np.concatenate((mat1,mat2))
print(mat3)
mat3=np.concatenate((mat1,mat2),axis=1)
print(mat3)

[[ 1  2]
 [ 4  5]
 [11 22]
 [44 55]]
[[ 1  2 11 22]
 [ 4  5 44 55]]


In [41]:
arr=np.array((4,6,6,7))
x=np.where(arr>=6)
print(x[0])
x=np.where(arr==6)
print(x[0])
x=np.where(arr==9)
if(x[0].size>=1):
    print(x[0])
else:
    print("NotFound")



[1 2 3]
[1 2]
NotFound
